### ISSUE TITLE
Process groups altogether

### ISSUE THREAD

**Issue by arrigonialberto86** [fstrozzi/bioruby-pipengine#30]
It would great to be able to specify a -G flag in order to process all the sample groups reported in samples.yml (this would generate the tree structure /Group_name/Sample_name for every sample)

**Comment by fstrozzi** [comment]
Resolved with commit https://github.com/fstrozzi/bioruby-pipengine/commit/d7f0800233f0ac6782ea5c3f2a951ff7f91281df
