### ISSUE TITLE
Groups processing (Cuffdiff, Cuffnorm)

### ISSUE THREAD

**Issue by arrigonialberto86** [fstrozzi/bioruby-pipengine#31]
It would be useful to parse sample groups information directly from samples.yml instead of defining them by hand using -m, so that
```pipengine -p pipeline.yml -m SampleA,SampleB SampleC,SampleB```
could be turned into:
```pipengine -p pipeline.yml -m config```

**Comment by fstrozzi** [comment]
Resolved with commit https://github.com/fstrozzi/bioruby-pipengine/commit/d7f0800233f0ac6782ea5c3f2a951ff7f91281df
