### ISSUE TITLE
check if all resources has been provided

### ISSUE THREAD

**Issue by rgiannico** [fstrozzi/bioruby-pipengine#32]
All pipelines has "pipeline resources" described into pipeline.yml file,
but they expect to find some "samples resources" described into samples.yml file too.
It will be nice if pipengine could check if all resources has been provided and all placeholder has been replaced.

**Comment by helios** [comment]
+1

**Comment by fstrozzi** [comment]
Closed with https://github.com/fstrozzi/bioruby-pipengine/commit/88b1665b5782d5a81b98c5bafd2da1ee2abd5a5d
