### ISSUE TITLE
Step dependencies (other step files)

### ISSUE THREAD

**Issue by rgiannico** [fstrozzi/bioruby-pipengine#33]
Each step could **require** something to be executed.
Generally step dependencies are **files** generated from previous steps.
You could specify required files using a "require" step feature AND/OR pipengine could directly infer required files parsing the command line. 

example of a step from *pipengine.yml* file:
```sh
blasting:
  require: <previousstep/sample>.query.fasta
  run: <blastn> -query <previousstep/sample>.query.fasta -task megablast -db <referenceblastdb> -out blastoutput.txt -outfmt 6  -num_threads <cpu>
  cpu: 8
```

**Comment by helios** [comment]
we have now
   pre: step_name

with "require" do you mean that automatically check if that file exist and if not call the step which generates it ?
"pre" should work in that case or we could combine them

**Comment by rgiannico** [comment]
Yes, i think file dependencies could be combined to step dependencies into your "pre" tag. 
About this, I think there could be only a couple of borderline cases to keep in mind if file dependencies will be included : 
Example using  " pre:  <previousstep/sample>.query.fasta "  
#case1: in this yml file doesn't exist any "previousstep" step
#case2: previousstep has been launched but the required file is missing
=> I think in both cases the best solution could be: pipengine exits with an error
=> what about another pipengine parameter like "--dont-climb-the-waterfalls" to avoid launching previous dependecy steps but simply exit with an error like "required step/file not found" ? It can be useful to have more control when creating or debugging new pipelines or to test if dependencies are working well.

**Comment by fstrozzi** [comment]
Enhancement included with commit https://github.com/fstrozzi/bioruby-pipengine/commit/fc03064f2b221221349506df69a78cb9eaaf8b71
