### ISSUE TITLE
single step 'local resources' directly from pipengine command line

### ISSUE THREAD

**Issue by rgiannico** [fstrozzi/bioruby-pipengine#34]
We have the 'global' pipeline resources, what about single step 'local' resources? 
Each step could have 'local variables' placeholders for some software parameters (like it is already implemented now for 'cpu' and 'mem' tags) and those variables could be directly overwritten wen launching pipengine. It could be very useful if you need to explore a range of values effect for a single parameter into the command line. 

example of a step into a  *pipeline.yml* file:
```sh
blasting:
  run: <blastn> -query <previousstep/sample>.query.fasta -task megablast -db <referenceblastdb> -out blastoutput.txt -outfmt 6 -max_target_seqs <hitsnumber> -num_threads <cpu>
  cpu: 8
  hitsnumber: 10
```
nice example alternatives for pipengine command line:
```sh
pipengine run -p pipeline.yml -s blasting -hitsnumber 5 
pipengine run -p pipeline.yml -s blasting -parameters [hitsnumber 5 , cpu 2] 
```

**Comment by fstrozzi** [comment]
Enhancement included with version https://github.com/fstrozzi/bioruby-pipengine/releases/tag/v0.9.0
