### ISSUE TITLE
Generate scripts even if Torque/PBS is not specified

### ISSUE THREAD

**Issue by biorelated** [fstrozzi/bioruby-pipengine#35]
Is it possible to configure PipEngine to simply generate step definitions and bash scripts even if Torque/PBS is not installed? I find it such a convenient way of generating and documenting workflows. 

So I am wondering if it may also be nice to be able to generate scripts to run on a machine without a scheduling system. At the moment or unless am missing something, one  requires a scheduling tool beforehand. 

am trying to imagine this 
`pipengine --no-torque run -c /data/illumina `

`pipenengine --no-torque run -p pipeline.yml -f samples.yml -s mapping --tmp /tmp`

**Comment by fstrozzi** [comment]
Hi,
if you use the option --dry (-d) Pipengine will generate runnable scripts without submitting them to Torque. I am also working on a lighter version of Pipengine, without the specific dependency on Torque and that will not require to connect via ssh to a master node to run the jobs. You can find it in the branch "no-torque".

**Comment by biorelated** [comment]
Thanks @fstrozzi! I will check out that branch.

**Comment by fstrozzi** [comment]
Hi,
this is just a small update since from version v0.8.0 the connection via ssh to a masternode is no longer supported by default, this simplifying the usage.
